# Generated by Django 3.0.2 on 2020-01-27 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_job_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job_size',
            name='job_size',
            field=models.CharField(choices=[('30', '0-$400'), ('29', '$400-$1000'), ('28', '$1000 - $3000'), ('27', '$3,000-$5,000'), ('26', '$5,000-$10,000'), ('25', '$10,000 - $25,000'), ('24', '$25,000 - $50,000'), ('23', '$25,000 - $50,000')], max_length=100),
        ),
    ]
