# Generated by Django 3.0.2 on 2020-01-27 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20200127_1626'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Job_Size',
            new_name='Price_form',
        ),
    ]
