# Generated by Django 3.0.2 on 2020-01-28 06:40

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20200127_1712'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company_Size',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_size', multiselectfield.db.fields.MultiSelectField(choices=[('30', '0-$400'), ('29', '$400-$1000'), ('28', '$1000 - $3000'), ('27', '$3,000-$5,000'), ('26', '$5,000-$10,000'), ('25', '$10,000 - $25,000'), ('24', '$25,000 - $50,000'), ('23', '$25,000 - $50,000')], max_length=23)),
            ],
        ),
        migrations.CreateModel(
            name='Credit_Days',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', multiselectfield.db.fields.MultiSelectField(choices=[('0', 'Advance Payment'), ('1.0', '21 days Credit'), ('2.0', '30 days Credit'), ('2.5', '45 days Credit'), ('3', '60 days Credit')], max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Manpower_Util',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manpower_util', multiselectfield.db.fields.MultiSelectField(choices=[('-10', '110'), ('0', '90'), ('10', '80'), ('20', '70'), ('25', '60')], max_length=14)),
            ],
        ),
        migrations.CreateModel(
            name='Priority',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', multiselectfield.db.fields.MultiSelectField(choices=[('15', '1.1'), ('10', '1'), ('5', '2'), ('0', '3')], max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='Requirement_Specification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('req_spec', multiselectfield.db.fields.MultiSelectField(choices=[('100', 'Hardly any definition'), ('40', 'Roughly Defined'), ('20', 'Clearly Defined'), ('10', 'Clearly defined with Disclaimer'), ('0', 'Manmonth')], max_length=14)),
            ],
        ),
        migrations.CreateModel(
            name='Turnaround_Time',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turnaround_time', multiselectfield.db.fields.MultiSelectField(choices=[('10', 'Very Quck'), ('5', 'Quick'), ('0', 'Average')], max_length=6)),
            ],
        ),
        migrations.RenameModel(
            old_name='Price_form',
            new_name='Job_Size',
        ),
    ]
